name: easy_eats
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  dio: ^5.2.1+1
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  flutter_svg: ^2.0.7
  flutter_form_builder: ^9.0.0
  flutter_slidable: ^3.0.0
  flutter_dotenv: ^5.1.0
  form_builder_validators: ^9.0.0
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  #background_image: "assets/background.png
  image: assets/images/splash_app.png
  android_12:  
    # Splash screen background color.
    #color: "#42a5f5"
    # App icon background color.
    #icon_background_color: "#111111"

  android: true
  ios: true
  web: true


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 