// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi7Hgo9P8oQPsGMz4x2fCrHoG462snnoU',
    appId: '1:861974945290:web:78b31c0494f45bc0c249f3',
    messagingSenderId: '861974945290',
    projectId: 'easy-eats-49695',
    authDomain: 'easy-eats-49695.firebaseapp.com',
    storageBucket: 'easy-eats-49695.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD43TOhB2eYPuCCUfdYaNbq0JT_-aVzhD0',
    appId: '1:861974945290:android:8e0824bf97633bc2c249f3',
    messagingSenderId: '861974945290',
    projectId: 'easy-eats-49695',
    storageBucket: 'easy-eats-49695.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzO7YJivMtLIB6HMGI9SUiSn4AHygyzPg',
    appId: '1:861974945290:ios:dfee0103f6c0f70cc249f3',
    messagingSenderId: '861974945290',
    projectId: 'easy-eats-49695',
    storageBucket: 'easy-eats-49695.appspot.com',
    androidClientId: '861974945290-nm02io1glee3527f3ckrql5tkc3c1ooo.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyEats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzO7YJivMtLIB6HMGI9SUiSn4AHygyzPg',
    appId: '1:861974945290:ios:9c9c375471228926c249f3',
    messagingSenderId: '861974945290',
    projectId: 'easy-eats-49695',
    storageBucket: 'easy-eats-49695.appspot.com',
    androidClientId: '861974945290-nm02io1glee3527f3ckrql5tkc3c1ooo.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyEats.RunnerTests',
  );
}
